export default [
    {
        id: 1,
        title: "",
        location: "",
        googleMapsLink: "",
        startDate: "",
        endDate: "",
        description: "",
        imageUrl: "",
    },
    {
        id: 1,
        title: "",
        location: "",
        googleMapsLink: "",
        startDate: "",
        endDate: "",
        description: "",
        imageUrl: "",
    },
    {
        id: 1,
        title: "",
        location: "",
        googleMapsLink: "",
        startDate: "",
        endDate: "",
        description: "",
        imageUrl: "",
    },
    {
        id: 1,
        title: "",
        location: "",
        googleMapsLink: "",
        startDate: "",
        endDate: "",
        description: "",
        imageUrl: "",
    }
]